### ISSUE TITLE
Errors when creating a protocol with one item

### ISSUE THREAD

**Issue by ibevers** [ReproNim/reproschema-ui#337] opened 2024-08-12 19:47 UTC
### protocol with one item (passes validation):
```
{
    "@context": [
        "https://raw.githubusercontent.com/ReproNim/reproschema/1.0.0/contexts/reproschema"
    ],
    "@type": "reproschema:Protocol",
    "@id": "test_protocol_schema",
    "prefLabel": "Test protocol",
    "description": "A test protocol",
    "schemaVersion": "1.0.0",
    "version": "0.0.1",
    "ui": {
        "addProperties": [
            {
                "isAbout": "generic/activities/q_generic_demographics/activities/completed_by/completed_by_schema",
                "variableName": "completed_by_schema",
                "prefLabel": {
                    "en": "completed_by"
                }
            }
        ],
        "order": [
            "generic/activities/q_generic_demographics/activities/completed_by/completed_by_schema"
        ],
        "shuffle": false,
        "allow": [
            "reproschema:AllowExport",
            "reproschema:AutoAdvance"
        ]
    }
}
```

### Error message:
<img width="1703" alt="Screenshot 2024-08-12 at 3 41 34 PM" src="https://github.com/user-attachments/assets/18e7ca63-bc4b-404a-8350-82b41058d687">

**Comment by satra** [comment] 2024-08-12 20:29
i’m not seeing the error with the single activity. i’m testing on my local setup with the docker container and a local repo of the `demo_protocol`. hence perhaps some component of the files you are testing with is probably not valid. can you try something like: `reproschema convert --format turtle DemoProtocol/DemoProtocol_schema_single` to see if you can spot any issues with the files? (also id check is not available in the current validation - still an open issue). 

feel free to post the turtles corresponding to either the activity or the protocol in this thread.

**Comment by ibevers** [comment] 2024-08-12 20:43
Hmm, weird I copy pasted my protocol and tried it again and it worked as expected. The turtle looks fine:
```

(.venv) isaacbevers@MacBook-Pro-8 b2aiprotocol % reproschema convert --format turtle  /Users/isaacbevers/sensein/reproschema-wrapper/b2aiprotocol/test_protocol
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rs: <http://schema.repronim.org/> .
@prefix sdo: <http://schema.org/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://localhost:8000//Users/isaacbevers/sensein/reproschema-wrapper/b2aiprotocol/test_protocol_schema> a rs:Protocol ;
    sdo:description "A test protocol"@en ;
    sdo:schemaVersion "1.0.0" ;
    sdo:version "0.0.1" ;
    rs:addProperties [ rs:isAbout <http://localhost:8000//Users/isaacbevers/sensein/reproschema-wrapper/b2aiprotocol/generic/activities/q_generic_demographics/activities/completed_by/completed_by_schema> ;
            rs:variableName "completed_by_schema"@en ;
            skos:prefLabel "completed_by"@en ] ;
    rs:allow rs:AllowExport,
        rs:AutoAdvance ;
    rs:order ( <http://localhost:8000//Users/isaacbevers/sensein/reproschema-wrapper/b2aiprotocol/generic/activities/q_generic_demographics/activities/completed_by/completed_by_schema> ) ;
    rs:shuffle false ;
    skos:prefLabel "Test protocol"@en .
```

**Comment by satra** [comment] 2024-08-12 20:47
i'll close this. reopen if it appears again.

**Closed by satra** 2024-08-12 20:47 UTC

**Comment by ibevers** [comment] 2024-08-14 17:48
@satra I don't have permission to reopen, but this error is back.

**Comment by satra** [comment] 2024-08-14 17:56
i could not reproduce it so i will need a minimal example that i can clone and reproduce.

**Comment by satra** [comment] 2024-08-14 17:56
also because of caching and other issues, make sure to clear out any cache and refresh.

**Comment by ibevers** [comment] 2024-08-15 14:35
I tried clearing my browser cache. I can work around this one, so I'm not going to put more effort into solving it for now
